import streamlit as st

# ---- STREAMLIT UI ----
st.set_page_config(page_title="Review Impact Calculator", page_icon="⭐", layout="centered")

# Session State for Managing Visibility
if "submitted" not in st.session_state:
    st.session_state.submitted = False

# Show title & instructions only if form has NOT been submitted
if not st.session_state.submitted:
    st.markdown("<h2 style='text-align: center;'>⭐ Review Impact Calculator</h2>", unsafe_allow_html=True)

    st.markdown(
        """
        🔹 Enter your **current Google rating**, **number of reviews**, and **target rating**.  
        🔹 Adjust your **customer lifetime value** to see how increasing your rating impacts revenue.  
        🔹 Click **"Calculate"** to generate your results.  
        """,
        unsafe_allow_html=True
    )

# FORM: User enters data
if not st.session_state.submitted:
    with st.form("review_calculator_form"):
        current_rating = st.slider("⭐ Current Google Rating", 1.0, 5.0, 4.00, 0.01)
        total_reviews = st.number_input("📌 Current Number of Google Reviews", min_value=1, value=50, step=1)
        target_rating = st.slider("🎯 Desired Google Rating", 1.0, 5.0, 4.6, 0.01)
        clv = st.number_input("💰 Customer Lifetime Value ($)", min_value=10, value=100, step=10)

        # Submit Button
        submitted = st.form_submit_button("Calculate")

        if submitted:
            st.session_state.submitted = True
            st.session_state.current_rating = current_rating
            st.session_state.total_reviews = total_reviews
            st.session_state.target_rating = target_rating
            st.session_state.clv = clv
            st.rerun()

# Show results if submitted
if st.session_state.submitted:
    def calculate_new_rating(current_rating, total_reviews, target_rating):
        """
        Calculates the number of 5-star reviews needed to reach the target rating.
        """
        current_total = current_rating * total_reviews
        new_reviews_needed = 0

        while (current_total + (5 * new_reviews_needed)) / (total_reviews + new_reviews_needed) < target_rating:
            new_reviews_needed += 1

        return new_reviews_needed

    def estimate_revenue_increase(new_reviews_needed, clv):
        """
        Estimates the additional revenue generated by acquiring more reviews.
        Assumes each review gets ~50 views per month and influences potential buyers.
        """
        return new_reviews_needed * 50 * 0.02 * clv  # 50 views/month * 2% conversion * CLV

    # Retrieve stored values
    reviews_needed = calculate_new_rating(st.session_state.current_rating, st.session_state.total_reviews, st.session_state.target_rating)
    revenue_increase = estimate_revenue_increase(reviews_needed, st.session_state.clv)

    # 📊 Results Display: Reviews Needed
    st.markdown("---")
    st.markdown(
        f"""
        <div style="background-color: #EFF8F0; padding: 16px; border-radius: 8px; text-align: center;">
            <h4 style="color: #28a745;">Your Results</h4>
            <h1 style="font-size: 72px; font-weight: bold;">{reviews_needed}</h1>
            <p style="font-size: 20px; color: #555;">5-star reviews needed to achieve a <strong>{st.session_state.target_rating}</strong> star rating.</p>
        </div>
        """,
        unsafe_allow_html=True
    )

    # 📈 Styled Revenue Impact
    st.markdown("---")
    st.markdown(
        f"""
        <div style="background-color: #FFF3CD; padding: 16px; border-radius: 8px; text-align: center;">
            <h4 style="color: #D39E00;">Revenue Impact</h4>
            <h1 style="font-size: 72px; font-weight: bold;">${revenue_increase:,.2f}</h1>
            <p style="font-size: 20px; color: #555;">Estimated monthly revenue increase.</p>
        </div>
        """,
        unsafe_allow_html=True
    )

    # 🎯 Call-To-Action Section
    st.markdown("---")
    st.subheader("🚀 Want to Increase Your Google Rating?")

    st.markdown(
        """
        📈 More **5-star reviews** = More **visibility**, More **trust**, and More **customers**.  
        🔥 Get **expert guidance** to improve your online reputation and **maximize revenue**.
        
        **Book a 30-minute session for $40 USD** and learn:  
        ✅ How to **get more 5-star reviews efficiently**  
        ✅ How to **handle negative reviews** without hurting your business  
        ✅ How to **optimize your Google Business Profile** for better rankings  
        """,
        unsafe_allow_html=True
    )

    # 🔗 Clickable CTA Button (Mobile-Optimized)
    st.markdown(
        """
        <div style="text-align:center;">
            <a href="https://tidycal.com/m52nvnm/30-minute-meeting" target="_blank">
                <button style="background-color:#28a745; border:none; color:white; padding:14px 28px;
                text-align:center; text-decoration:none; display:inline-block; font-size:18px;
                margin:12px 2px; cursor:pointer; border-radius:8px; width:90%;">
                📅 Book a 30-Minute Reputation Growth Session – $40
                </button>
            </a>
        </div>
        """,
        unsafe_allow_html=True
    )
