import streamlit as st
import math

def calculate_new_rating(current_rating, total_reviews, target_rating):
    """
    Calculates the number of 5-star reviews needed to reach the target rating.
    """
    current_total = current_rating * total_reviews
    new_reviews_needed = 0

    while (current_total + (5 * new_reviews_needed)) / (total_reviews + new_reviews_needed) < target_rating:
        new_reviews_needed += 1

    return new_reviews_needed

def estimate_revenue_increase(current_reviews, additional_reviews, clv):
    """
    Estimates the additional revenue generated by acquiring more reviews.
    Assumes each review gets ~2000 views per year and influences potential buyers.
    """
    estimated_revenue = additional_reviews * clv * 2000 * 0.01  # Assuming 1% conversion
    return estimated_revenue

def estimate_ctr_boost(current_rating, new_rating):
    """
    Estimates the percentage increase in click-through rate (CTR) when rating improves.
    """
    ctr_data = {4.0: 5, 4.2: 8, 4.5: 15, 4.7: 20, 4.9: 30}
    return ctr_data.get(new_rating, 0) - ctr_data.get(current_rating, 0)

# Streamlit UI
st.title("📊 Review Insights Calculator")

st.sidebar.header("Input Your Business Data")
current_rating = st.sidebar.slider("Current Star Rating", 1.0, 5.0, 4.5, 0.1)
total_reviews = st.sidebar.number_input("Total Number of Reviews", min_value=1, value=200, step=1)
target_rating = st.sidebar.slider("Target Star Rating", 1.0, 5.0, 4.6, 0.1)
clv = st.sidebar.number_input("Average Customer Lifetime Value ($)", min_value=10, value=1000, step=10)
additional_reviews = st.sidebar.number_input("Number of Additional Reviews Expected", min_value=1, value=100, step=10)

# Calculations
reviews_needed = calculate_new_rating(current_rating, total_reviews, target_rating)
revenue_increase = estimate_revenue_increase(total_reviews, additional_reviews, clv)
ctr_boost = estimate_ctr_boost(current_rating, target_rating)

# Display results
st.subheader("🔍 Review Growth Insights")
st.write(f"⭐ **5-Star Reviews Needed to Reach {target_rating}:** {reviews_needed}")
st.write(f"💰 **Estimated Revenue Increase with {additional_reviews} More Reviews:** ${revenue_increase:,.2f}")
st.write(f"📈 **Estimated Click-Through Rate Boost:** {ctr_boost}%")

st.markdown("---")
st.markdown("💡 *Improve your online presence and grow your business with better reviews!*")

